# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.add("DiffEqBase")'
  - julia -e 'Pkg.add("DiffEqPDEBase")'
  - julia -e 'Pkg.add("DiffEqProblemLibrary")'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("DiffEqDocs")); include(joinpath("docs", "make.jl"))'
