site_name:           DifferentialEquations.jl
repo_url:            https://github.com/JuliaDiffEq/DifferentialEquations.jl
site_description:    Julia package for solving differential equations
site_author:         Chris Rackauckas
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  #- mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorials:
  - Ordinary Differential Equation Example: tutorials/ode_example.md
  - Stochastic Differential Equation Example: tutorials/sde_example.md
  - Poisson Equation Finite Element Method Example: tutorials/fempoisson_example.md
  - Heat Equation Finite Element Method Example: tutorials/femheat_example.md
  - Stochastic Finite Element Examples: tutorials/femstochastic_example.md
- Solver Options:
  - Ordinary Differential Equation Solvers: solvers/ode_solve.md
  - Stochastic Differential Equation Solvers: solvers/sde_solve.md
  - Poisson Equation Finite Element Method Solvers: solvers/fempoisson_solve.md
  - Heat Equation Finite Element Method Solvers: solvers/femheat_solve.md
  - Stationary Stokes Equation Finite Difference Method Solvers: solvers/fdmstokes_solve.md
- Manual:
  - Overview of DifferentialEquations.jl Usage: man/overview.md
  - Defining an ODE Problem: man/ODEProblem.md
  - Defining an SDE Problem: man/SDEProblem.md
  - Defining a Finite Element Problem: man/FEMProblem.md
  - Defining a Stokes Problem: man/StokesProblem.md
  - Meshes: man/mesh.md
  - The Solution Type: man/solution.md
  - Plot Functions: man/plot.md
  - Function Definition Macros: man/function_definition_macros.md
  - Benchmark Suite: man/benchmarks.md
  - Convergence Simuations: man/convergence.md
  - Conditional Dependencies: man/conditional_dependencies.md
  - Juno Progress Bar Integration: man/progress_bar.md
- Internal Documentation:
  - Contributor's Guide: internals/contributors_guide.md
  - Internal Finite Element Tools: internals/fem_tools.md
  - Extra Functions: internals/extras.md
  - Solver Helpers: internals/solver_helpers.md
  - Notes on Algorithms: internals/notes_on_algorithms.md
